"""Guards ``docs/tool_reference.md`` against drift.

The reference is generated by ``scripts/gen_tool_reference.py`` from the
live MCP server tool registrations. If a tool description or schema changes
without regenerating, this test fails and points at ``make docs``.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))


def test_tool_reference_is_in_sync() -> None:
    from gen_tool_reference import render

    expected = render()
    actual = (REPO_ROOT / "docs" / "tool_reference.md").read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/tool_reference.md is out of date. Run `make docs` and commit the updated file."
    )
